import {
  Home, Landmark, Wallet, CreditCard, Banknote,
  Briefcase, Monitor, TrendingUp, Gift, Plus,
  Utensils, Car, Heart, Gamepad2, User,
  BookOpen, Package, ShoppingCart, Plane, Film,
  Music, Dumbbell, Coffee, Shirt, Wrench,
  Zap, Star, Tag, Repeat, PiggyBank,
  ShoppingBag, Baby, Dog, Building2, Globe,
  type LucideIcon,
} from "lucide-react";

export const ICONO_MAP: Record<string, LucideIcon> = {
  "home":          Home,
  "landmark":      Landmark,
  "wallet":        Wallet,
  "credit-card":   CreditCard,
  "banknote":      Banknote,
  "briefcase":     Briefcase,
  "monitor":       Monitor,
  "trending-up":   TrendingUp,
  "gift":          Gift,
  "plus":          Plus,
  "utensils":      Utensils,
  "car":           Car,
  "heart":         Heart,
  "gamepad-2":     Gamepad2,
  "user":          User,
  "book-open":     BookOpen,
  "package":       Package,
  "shopping-cart": ShoppingCart,
  "plane":         Plane,
  "film":          Film,
  "music":         Music,
  "dumbbell":      Dumbbell,
  "coffee":        Coffee,
  "shirt":         Shirt,
  "wrench":        Wrench,
  "zap":           Zap,
  "star":          Star,
  "tag":           Tag,
  "repeat":        Repeat,
  "piggy-bank":    PiggyBank,
  "shopping-bag":  ShoppingBag,
  "baby":          Baby,
  "dog":           Dog,
  "building-2":    Building2,
  "globe":         Globe,
};

export const ICONOS = Object.keys(ICONO_MAP);
