"""tablas cuentas categorias etiquetas movimientos

Revision ID: 4d618d677998
Revises: 57eb8bfd2430
Create Date: 2026-05-10 03:47:15.773146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d618d677998'
down_revision: Union[str, Sequence[str], None] = '57eb8bfd2430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('archivado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_workspace_id'), 'categorias', ['workspace_id'], unique=False)
    op.create_table('cuentas',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('fecha_saldo_inicial', sa.Date(), nullable=False),
    sa.Column('modo_saldo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('saldo_manual', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('institucion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('iban_ultimos4', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('incluir_en_patrimonio', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('archivado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_workspace_id'), 'cuentas', ['workspace_id'], unique=False)
    op.create_table('etiquetas',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etiquetas_workspace_id'), 'etiquetas', ['workspace_id'], unique=False)
    op.create_table('movimientos',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cuenta_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('importe', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('importe_base', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tasa_cambio', sa.Numeric(precision=18, scale=8), server_default='1', nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('concepto', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('transferencia_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fuente', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('fuente_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('hash_idempotencia', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('archivado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_idempotencia')
    )
    op.create_index(op.f('ix_movimientos_categoria_id'), 'movimientos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_movimientos_cuenta_id'), 'movimientos', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_movimientos_fecha'), 'movimientos', ['fecha'], unique=False)
    op.create_index(op.f('ix_movimientos_workspace_id'), 'movimientos', ['workspace_id'], unique=False)
    op.create_table('movimientos_etiquetas',
    sa.Column('movimiento_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('etiqueta_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiquetas.id'], ),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos.id'], ),
    sa.PrimaryKeyConstraint('movimiento_id', 'etiqueta_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos_etiquetas')
    op.drop_index(op.f('ix_movimientos_workspace_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_fecha'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_cuenta_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_categoria_id'), table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_etiquetas_workspace_id'), table_name='etiquetas')
    op.drop_table('etiquetas')
    op.drop_index(op.f('ix_cuentas_workspace_id'), table_name='cuentas')
    op.drop_table('cuentas')
    op.drop_index(op.f('ix_categorias_workspace_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
