"""tipos_cambio y transferencias

Revision ID: 4fc2955e0428
Revises: 131def91be63
Create Date: 2026-05-10 04:01:16.694293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4fc2955e0428'
down_revision: Union[str, Sequence[str], None] = '131def91be63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_cambio',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moneda_origen', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('moneda_destino', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('tasa', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fuente', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('moneda_origen', 'moneda_destino', 'fecha', name='uq_tipo_cambio')
    )
    op.create_index(op.f('ix_tipos_cambio_fecha'), 'tipos_cambio', ['fecha'], unique=False)
    op.create_index(op.f('ix_tipos_cambio_moneda_destino'), 'tipos_cambio', ['moneda_destino'], unique=False)
    op.create_index(op.f('ix_tipos_cambio_moneda_origen'), 'tipos_cambio', ['moneda_origen'], unique=False)
    op.create_table('transferencias',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('movimiento_origen_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('movimiento_destino_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movimiento_destino_id'], ['movimientos.id'], ),
    sa.ForeignKeyConstraint(['movimiento_origen_id'], ['movimientos.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transferencias_workspace_id'), 'transferencias', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transferencias_workspace_id'), table_name='transferencias')
    op.drop_table('transferencias')
    op.drop_index(op.f('ix_tipos_cambio_moneda_origen'), table_name='tipos_cambio')
    op.drop_index(op.f('ix_tipos_cambio_moneda_destino'), table_name='tipos_cambio')
    op.drop_index(op.f('ix_tipos_cambio_fecha'), table_name='tipos_cambio')
    op.drop_table('tipos_cambio')
    # ### end Alembic commands ###
