"""tablas usuarios y workspaces

Revision ID: 57eb8bfd2430
Revises: 
Create Date: 2026-05-10 03:03:03.419855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '57eb8bfd2430'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usuario_unico', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('avatar_emoji', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_usuario_unico'), 'usuarios', ['usuario_unico'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('moneda_base', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('archivado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_table('workspace_miembros',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usuario_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('unido_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_miembros_usuario_id'), 'workspace_miembros', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_workspace_miembros_workspace_id'), 'workspace_miembros', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_miembros_workspace_id'), table_name='workspace_miembros')
    op.drop_index(op.f('ix_workspace_miembros_usuario_id'), table_name='workspace_miembros')
    op.drop_table('workspace_miembros')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_usuarios_usuario_unico'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
