"""add_cuenta_id_to_objetivo_aportaciones

Revision ID: 650c592cb389
Revises: 9fde6ebaad37
Create Date: 2026-05-10 23:57:16.727313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650c592cb389'
down_revision: Union[str, Sequence[str], None] = '9fde6ebaad37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objetivo_aportaciones', sa.Column('cuenta_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objetivo_aportaciones', 'cuenta_id')
    # ### end Alembic commands ###
