"""amigos_y_gastos_compartidos

Revision ID: 853f69f4684e
Revises: b497e4f77d95
Create Date: 2026-05-10 10:24:31.224786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '853f69f4684e'
down_revision: Union[str, Sequence[str], None] = 'b497e4f77d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amigos',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('solicitante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receptor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receptor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amigos_receptor_id'), 'amigos', ['receptor_id'], unique=False)
    op.create_index(op.f('ix_amigos_solicitante_id'), 'amigos', ['solicitante_id'], unique=False)
    op.create_table('amigos_externos',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_por', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('usuario_real_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('archivado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_real_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amigos_externos_creado_por'), 'amigos_externos', ['creado_por'], unique=False)
    op.create_table('grupos',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('moneda_principal', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('es_cuenta_real', sa.Boolean(), nullable=False),
    sa.Column('cuenta_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('modo_reparto_default', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('creado_por', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(), nullable=True),
    sa.Column('archivado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_miembros',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grupo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usuario_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('externo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('apodo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('salido_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['externo_id'], ['amigos_externos.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_miembros_grupo_id'), 'grupo_miembros', ['grupo_id'], unique=False)
    op.create_table('gastos_compartidos',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grupo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('concepto', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('importe', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('importe_convertido', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tasa_cambio', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pagador_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modo_reparto', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('afecta_cuenta_personal', sa.Boolean(), nullable=False),
    sa.Column('movimiento_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cuenta_personal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creado_por', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('archivado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cuenta_personal_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos.id'], ),
    sa.ForeignKeyConstraint(['pagador_id'], ['grupo_miembros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_compartidos_grupo_id'), 'gastos_compartidos', ['grupo_id'], unique=False)
    op.create_table('liquidaciones',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grupo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('de_miembro_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('a_miembro_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('movimiento_pago_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('movimiento_cobro_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('confirmado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['a_miembro_id'], ['grupo_miembros.id'], ),
    sa.ForeignKeyConstraint(['de_miembro_id'], ['grupo_miembros.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['movimiento_cobro_id'], ['movimientos.id'], ),
    sa.ForeignKeyConstraint(['movimiento_pago_id'], ['movimientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidaciones_grupo_id'), 'liquidaciones', ['grupo_id'], unique=False)
    op.create_table('gastos_repartos',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gasto_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('miembro_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('importe_asignado', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('partes', sa.Integer(), nullable=True),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos_compartidos.id'], ),
    sa.ForeignKeyConstraint(['miembro_id'], ['grupo_miembros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_repartos_gasto_id'), 'gastos_repartos', ['gasto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gastos_repartos_gasto_id'), table_name='gastos_repartos')
    op.drop_table('gastos_repartos')
    op.drop_index(op.f('ix_liquidaciones_grupo_id'), table_name='liquidaciones')
    op.drop_table('liquidaciones')
    op.drop_index(op.f('ix_gastos_compartidos_grupo_id'), table_name='gastos_compartidos')
    op.drop_table('gastos_compartidos')
    op.drop_index(op.f('ix_grupo_miembros_grupo_id'), table_name='grupo_miembros')
    op.drop_table('grupo_miembros')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_amigos_externos_creado_por'), table_name='amigos_externos')
    op.drop_table('amigos_externos')
    op.drop_index(op.f('ix_amigos_solicitante_id'), table_name='amigos')
    op.drop_index(op.f('ix_amigos_receptor_id'), table_name='amigos')
    op.drop_table('amigos')
    # ### end Alembic commands ###
