"""add_foto_data_to_usuarios

Revision ID: 98f66249bebe
Revises: 650c592cb389
Create Date: 2026-05-11 22:22:43.976623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f66249bebe'
down_revision: Union[str, Sequence[str], None] = '650c592cb389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('foto_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'foto_data')
    # ### end Alembic commands ###
