"""reglas_motor_v2

Revision ID: 98fa99b2ba9d
Revises: d7675f3c8d3a
Create Date: 2026-05-10 10:42:37.331583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fa99b2ba9d'
down_revision: Union[str, Sequence[str], None] = 'd7675f3c8d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
