"""add auth_id to usuario

Revision ID: 9fde6ebaad37
Revises: be01c9808cf5
Create Date: 2026-05-10 11:50:29.695846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fde6ebaad37'
down_revision: Union[str, Sequence[str], None] = 'be01c9808cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('auth_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_usuarios_auth_id'), 'usuarios', ['auth_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_auth_id'), table_name='usuarios')
    op.drop_column('usuarios', 'auth_id')
    # ### end Alembic commands ###
