"""presupuestos y recurrentes

Revision ID: b497e4f77d95
Revises: 4fc2955e0428
Create Date: 2026-05-10 10:10:36.430365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b497e4f77d95'
down_revision: Union[str, Sequence[str], None] = '4fc2955e0428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presupuestos',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('importe', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('periodo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('modo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('categoria_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cuenta_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('archivado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuestos_workspace_id'), 'presupuestos', ['workspace_id'], unique=False)
    op.create_table('recurrentes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('importe', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('cuenta_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('frecuencia', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('dia_mes', sa.Integer(), nullable=True),
    sa.Column('proxima_ejecucion', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('archivado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurrentes_cuenta_id'), 'recurrentes', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_recurrentes_proxima_ejecucion'), 'recurrentes', ['proxima_ejecucion'], unique=False)
    op.create_index(op.f('ix_recurrentes_workspace_id'), 'recurrentes', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurrentes_workspace_id'), table_name='recurrentes')
    op.drop_index(op.f('ix_recurrentes_proxima_ejecucion'), table_name='recurrentes')
    op.drop_index(op.f('ix_recurrentes_cuenta_id'), table_name='recurrentes')
    op.drop_table('recurrentes')
    op.drop_index(op.f('ix_presupuestos_workspace_id'), table_name='presupuestos')
    op.drop_table('presupuestos')
    # ### end Alembic commands ###
